version: '3.3'

networks:
  prometheus:

services:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - /data/monitoring/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_SECURITY_ADMIN_USER=admin
    networks:
     - prometheus
    restart: always
